# Generated by Django 5.2.7 on 2025-10-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_order_orderitem_review_shippingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
