# Generated by Django 5.2.7 on 2025-11-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/sample.jpg", null=True, upload_to=""
            ),
        ),
    ]
